### ISSUE TITLE
vc4: partial asteroid rendering in glmark2.

### ISSUE THREAD

**Issue by anholt** [anholt/mesa#3]
From https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=135790:

See https://youtu.be/yVuIAmf8OEU?t=110

**Comment by ric96** [comment]
+1

**Comment by anholt** [comment]
OK, this is the GFXH-515 problem.  Cleaning up the fix now.

**Comment by anholt** [comment]
Fixed by 3b63301d9fff43119359eaeb34f80426919f0b4a

**Comment by ric96** [comment]
I tried with the VC4-loop branch but its still the same... 
Is my autogen ok? ./autogen.sh  --with-gallium-drivers=vc4  --with-dri-drivers=  --with-egl-platforms=x11,drm
if so, then which branch works?

**Comment by anholt** [comment]
I'm shocked that vc4-loop worked at all, and as a result I suspect you weren't really using the driver.

The fix is on master.

**Comment by ric96** [comment]
I did build master but it looks like X is not using the new driver, what prefix should i use?
